version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - task_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: process.env.MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: process.env.MYSQL_DATABASE
    ports:
      - "3306:3306"
    networks:
      - task_network
networks:
  task_network:
    driver: bridge
